# Generated by Django 3.0.5 on 2020-04-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200406_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='book',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Book'),
            preserve_default=False,
        ),
    ]
