# Generated by Django 3.0.5 on 2020-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_friend_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.SmallIntegerField(primary_key='True', serialize=False),
        ),
    ]
