# Generated by Django 3.0.5 on 2020-04-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200406_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Publishing'),
        ),
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.NullBooleanField(default=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(through='p_library.BookReading', to='p_library.Book'),
        ),
    ]
