# Generated by Django 3.0.5 on 2020-04-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20200407_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.SmallIntegerField(verbose_name='Год рожения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, verbose_name='Международный стандартный книжный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='p_library.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(verbose_name='Число копий'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_pub', to='p_library.Publishing', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.SmallIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='completion',
            field=models.NullBooleanField(default=None, verbose_name='Чтение завершено'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(through='p_library.BookReading', to='p_library.Book', verbose_name='Книги'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='publish_name',
            field=models.CharField(max_length=50, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='sity',
            field=models.CharField(max_length=20, verbose_name='Город'),
        ),
    ]
