# Generated by Django 3.0.5 on 2020-04-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_auto_20200407_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_read', to='p_library.Friend'),
        ),
    ]
