# Generated by Django 3.0.5 on 2020-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_book_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friends',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
